# The URL the site will be built for
base_url = "https://blog.sunnyg.io"

title = ""
description = ""
author = ""
default_language = "en"
theme = "after-dark"

render_emoji = true
generate_feed = true
minify_html = false
compile_sass = true
build_search_index = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false

output_dir = "public"
ignored_content = []
ignored_static = []

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
