# The URL the site will be built for
base_url = "https://sunnyg.io"

title = ""
description = ""
author = "Sunny Gonnabathula"
theme = "anemone"

default_language = "en"
generate_feed = true
feed_filename = "rss.xml"
build_search_index = true

minify_html = false
compile_sass = true
output_dir = "public"

ignored_content = []
ignored_static = []
taxonomies = [
  {name = "tags", feed = true},
  {name = "categories", paginate_by = 5},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false

[search]
include_title = true
include_description = true
include_path = true
include_content = false

[extra]
author = "Sunny Gonnabathula"
default_theme = "dark"
display_author = true
github = "sunny-g"
twitter_card = true
list_pages = true

header_nav = [
  {name_en = "Home", url = "/"},
  {name_en = "Blog", url = "/blog"},
  {name_en = "Github", url = "https://github.com/sunny-g"},
  {name_en = "Linkedin", url = "https://linkedin.com/in/sunnygonna"},
]
